# Generated by Django 3.2.18 on 2023-07-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('society_name', models.CharField(max_length=100)),
                ('flat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('services_required', models.CharField(blank=True, max_length=200, null=True)),
                ('other_services', models.CharField(blank=True, max_length=200, null=True)),
                ('house_size', models.CharField(max_length=50)),
                ('timings', models.CharField(max_length=100)),
                ('additional_requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('services_offered', models.TextField()),
                ('washroom_included', models.BooleanField(default=False)),
                ('available_slots', models.CharField(max_length=100)),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sunday_availability', models.BooleanField(default=False)),
                ('languages', models.CharField(max_length=200)),
                ('cooking_options', models.CharField(max_length=7)),
                ('speciality', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('additional_details', models.TextField()),
            ],
        ),
    ]
