# Generated by Django 3.2.18 on 2023-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Female', max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('start_date', models.DateField(null=True)),
                ('preferred_time_range_start', models.TimeField(null=True)),
                ('preferred_time_range_end', models.TimeField(null=True)),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sunday_availability', models.BooleanField()),
                ('languages', models.TextField()),
                ('experience', models.TextField()),
                ('additional_details', models.TextField()),
                ('cooking_options', models.TextField()),
                ('specialty', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nanny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Female', max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('start_date', models.DateField(null=True)),
                ('preferred_time_range_start', models.TimeField(null=True)),
                ('preferred_time_range_end', models.TimeField(null=True)),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sunday_availability', models.BooleanField()),
                ('languages', models.TextField()),
                ('experience', models.TextField()),
                ('additional_details', models.TextField()),
                ('childcare_experience', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='maid',
            name='address',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='age',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='cooking_options',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='washroom_included',
        ),
        migrations.AddField(
            model_name='maid',
            name='gender',
            field=models.CharField(default='Female', max_length=10),
        ),
        migrations.AddField(
            model_name='maid',
            name='preferred_time_range_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='maid',
            name='preferred_time_range_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='maid',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maid',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='maid',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maid',
            name='cost_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maid',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maid',
            name='languages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maid',
            name='sunday_availability',
            field=models.BooleanField(),
        ),
    ]
