# Generated by Django 3.2.18 on 2023-08-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0002_auto_20230813_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='count',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='society_name',
        ),
    ]
