# Generated by Django 3.2.18 on 2023-08-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0005_auto_20230815_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='available',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='maid',
            name='available',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='nanny',
            name='available',
            field=models.BooleanField(default=1),
        ),
    ]
