# Generated by Django 4.2.5 on 2023-09-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='country',
            field=models.CharField(default='Country', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Country', max_length=20),
        ),
        migrations.AddField(
            model_name='maid',
            name='country',
            field=models.CharField(default='Country', max_length=20),
        ),
        migrations.AddField(
            model_name='nanny',
            name='country',
            field=models.CharField(default='Country', max_length=20),
        ),
    ]
